name: Build and Distribute Release

on:
  release:
    types: [published]

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: LICENSE shaders/
          dest: "Visual-Vibrance-${{ github.event.release.tag_name }}.zip"
          recursive: false
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "Visual-Vibrance-${{ github.event.release.tag_name }}.zip"
          asset_name: "Visual-Vibrance-${{ github.event.release.tag_name }}.zip"
          tag: ${{ github.ref }}
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: l6Uqs2fS
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1244801
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files: "Visual-Vibrance-${{ github.event.release.tag_name }}.zip"
          loaders: iris
          game-versions: ">=1.20"

          
